### ISSUE TITLE
複製遊戲成績 button is not using local time

### ISSUE THREAD

**Issue by shion-kinos** [jonathan-lph/cidou#2]
The 複製遊戲成績 button is not using local time to calculate the game number. So when I played yesterday night it was game number 6, and this morning it was again game number 6.

**Comment by jonathan-lph** [comment]
Currently it is using milliseconds from date of creation (in UTC+8) to calculate the game number. Will look into changing it to local time later. 

Aside from the game number, is the game result correctly copied?

**Comment by shion-kinos** [comment]
Yes, the game result is copied correctly.
